name: AvengersAssemble
version: 1.0
api-version: 1.15
author: ocelot
main: uk.co.ayth.AvengersAssembleMain

commands:
  thor:
    description: Assign yourself to Thor
    usage: /thor
  removebossbar:
    description: ding dong
    usage: /removebossbar