name: AvengersAssemble
version: 1.0
api-version: 1.15
author: ocelot
main: uk.co.ayth.AvengersAssembleMain

commands:
  avenger:
    description: Assign yourself to an avenger
    usage: /avenger [avengername]
  avengerlist:
    description: Get list of current avengers
    usage: /avengerlist
  avengerremove:
    description: remove player from being an avenger
    usage: /avengerremove [playername]