name: AvengersAssemble
version: 1.0
api-version: 1.15
author: ocelot
main: uk.co.ayth.AvengersAssembleMain

commands:
  thor:
    description: Assign yourself to Thor
    usage: /thor
  whoisthor:
    description: Who Is Thor
    usage: /whoisthor
  unthorall:
    description: UnThor yaself
    usage: /unthorall
