name: AvengersAssemble
version: 1.0
api-version: 1.15
author: ocelot
main: uk.co.ayth.AvengersAssembleMain

commands:
  thor:
    description: Assign yourself to Thor
    usage: /thor
  hulk:
    description: Assign yourself to Hulk
    usage: /hulk